//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Autonav
{
    [Serializable]
    public class AudibleFeedbackMsg : Message
    {
        public const string k_RosMessageName = "autonav_msgs/AudibleFeedback";
        public override string RosMessageName => k_RosMessageName;

        public string filename;

        public AudibleFeedbackMsg()
        {
            this.filename = "";
        }

        public AudibleFeedbackMsg(string filename)
        {
            this.filename = filename;
        }

        public static AudibleFeedbackMsg Deserialize(MessageDeserializer deserializer) => new AudibleFeedbackMsg(deserializer);

        private AudibleFeedbackMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.filename);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.filename);
        }

        public override string ToString()
        {
            return "AudibleFeedbackMsg: " +
            "\nfilename: " + filename.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
