//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Autonav
{
    [Serializable]
    public class ConfigurationUpdateMsg : Message
    {
        public const string k_RosMessageName = "autonav_msgs/ConfigurationUpdate";
        public override string RosMessageName => k_RosMessageName;

        public string device;
        public string json;

        public ConfigurationUpdateMsg()
        {
            this.device = "";
            this.json = "";
        }

        public ConfigurationUpdateMsg(string device, string json)
        {
            this.device = device;
            this.json = json;
        }

        public static ConfigurationUpdateMsg Deserialize(MessageDeserializer deserializer) => new ConfigurationUpdateMsg(deserializer);

        private ConfigurationUpdateMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.device);
            deserializer.Read(out this.json);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.device);
            serializer.Write(this.json);
        }

        public override string ToString()
        {
            return "ConfigurationUpdateMsg: " +
            "\ndevice: " + device.ToString() +
            "\njson: " + json.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
