//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Autonav
{
    [Serializable]
    public class GPSFeedbackMsg : Message
    {
        public const string k_RosMessageName = "autonav_msgs/GPSFeedback";
        public override string RosMessageName => k_RosMessageName;

        public double latitude;
        public double longitude;
        public double altitude;
        public short gps_fix;
        public bool is_locked;
        public short satellites;

        public GPSFeedbackMsg()
        {
            this.latitude = 0.0;
            this.longitude = 0.0;
            this.altitude = 0.0;
            this.gps_fix = 0;
            this.is_locked = false;
            this.satellites = 0;
        }

        public GPSFeedbackMsg(double latitude, double longitude, double altitude, short gps_fix, bool is_locked, short satellites)
        {
            this.latitude = latitude;
            this.longitude = longitude;
            this.altitude = altitude;
            this.gps_fix = gps_fix;
            this.is_locked = is_locked;
            this.satellites = satellites;
        }

        public static GPSFeedbackMsg Deserialize(MessageDeserializer deserializer) => new GPSFeedbackMsg(deserializer);

        private GPSFeedbackMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.latitude);
            deserializer.Read(out this.longitude);
            deserializer.Read(out this.altitude);
            deserializer.Read(out this.gps_fix);
            deserializer.Read(out this.is_locked);
            deserializer.Read(out this.satellites);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.latitude);
            serializer.Write(this.longitude);
            serializer.Write(this.altitude);
            serializer.Write(this.gps_fix);
            serializer.Write(this.is_locked);
            serializer.Write(this.satellites);
        }

        public override string ToString()
        {
            return "GPSFeedbackMsg: " +
            "\nlatitude: " + latitude.ToString() +
            "\nlongitude: " + longitude.ToString() +
            "\naltitude: " + altitude.ToString() +
            "\ngps_fix: " + gps_fix.ToString() +
            "\nis_locked: " + is_locked.ToString() +
            "\nsatellites: " + satellites.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
