//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Autonav
{
    [Serializable]
    public class LogMsg : Message
    {
        public const string k_RosMessageName = "autonav_msgs/Log";
        public override string RosMessageName => k_RosMessageName;

        public ulong timestamp;
        public byte level;
        public string node;
        public string message;
        public string function_caller;
        public ushort line_number;

        public LogMsg()
        {
            this.timestamp = 0;
            this.level = 0;
            this.node = "";
            this.message = "";
            this.function_caller = "";
            this.line_number = 0;
        }

        public LogMsg(ulong timestamp, byte level, string node, string message, string function_caller, ushort line_number)
        {
            this.timestamp = timestamp;
            this.level = level;
            this.node = node;
            this.message = message;
            this.function_caller = function_caller;
            this.line_number = line_number;
        }

        public static LogMsg Deserialize(MessageDeserializer deserializer) => new LogMsg(deserializer);

        private LogMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.timestamp);
            deserializer.Read(out this.level);
            deserializer.Read(out this.node);
            deserializer.Read(out this.message);
            deserializer.Read(out this.function_caller);
            deserializer.Read(out this.line_number);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.timestamp);
            serializer.Write(this.level);
            serializer.Write(this.node);
            serializer.Write(this.message);
            serializer.Write(this.function_caller);
            serializer.Write(this.line_number);
        }

        public override string ToString()
        {
            return "LogMsg: " +
            "\ntimestamp: " + timestamp.ToString() +
            "\nlevel: " + level.ToString() +
            "\nnode: " + node.ToString() +
            "\nmessage: " + message.ToString() +
            "\nfunction_caller: " + function_caller.ToString() +
            "\nline_number: " + line_number.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
