//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Autonav
{
    [Serializable]
    public class MotorFeedbackMsg : Message
    {
        public const string k_RosMessageName = "autonav_msgs/MotorFeedback";
        public override string RosMessageName => k_RosMessageName;

        public double delta_x = 0;
        public double delta_y = 0;
        public double delta_theta = 0;

        public MotorFeedbackMsg()
        {
        }

        public MotorFeedbackMsg(double delta_x, double delta_y, double delta_theta)
        {
            this.delta_x = delta_x;
            this.delta_y = delta_y;
            this.delta_theta = delta_theta;
        }

        public static MotorFeedbackMsg Deserialize(MessageDeserializer deserializer) => new MotorFeedbackMsg(deserializer);

        private MotorFeedbackMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.delta_x);
            deserializer.Read(out this.delta_y);
            deserializer.Read(out this.delta_theta);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.delta_x);
            serializer.Write(this.delta_y);
            serializer.Write(this.delta_theta);
        }

        public override string ToString()
        {
            return "MotorFeedbackMsg: " +
            "\ndelta_x: " + delta_x.ToString() +
            "\ndelta_y: " + delta_y.ToString() +
            "\ndelta_theta: " + delta_theta.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
