//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Autonav
{
    [Serializable]
    public class NUCStatisticsMsg : Message
    {
        public const string k_RosMessageName = "autonav_msgs/NUCStatistics";
        public override string RosMessageName => k_RosMessageName;

        public uint timestamp;
        //  in milliseconds
        public float cpu_percentage;
        public float ram_usage;
        public float disk_usage;
        public float gpu_usage;

        public NUCStatisticsMsg()
        {
            this.timestamp = 0;
            this.cpu_percentage = 0.0f;
            this.ram_usage = 0.0f;
            this.disk_usage = 0.0f;
            this.gpu_usage = 0.0f;
        }

        public NUCStatisticsMsg(uint timestamp, float cpu_percentage, float ram_usage, float disk_usage, float gpu_usage)
        {
            this.timestamp = timestamp;
            this.cpu_percentage = cpu_percentage;
            this.ram_usage = ram_usage;
            this.disk_usage = disk_usage;
            this.gpu_usage = gpu_usage;
        }

        public static NUCStatisticsMsg Deserialize(MessageDeserializer deserializer) => new NUCStatisticsMsg(deserializer);

        private NUCStatisticsMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.timestamp);
            deserializer.Read(out this.cpu_percentage);
            deserializer.Read(out this.ram_usage);
            deserializer.Read(out this.disk_usage);
            deserializer.Read(out this.gpu_usage);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.timestamp);
            serializer.Write(this.cpu_percentage);
            serializer.Write(this.ram_usage);
            serializer.Write(this.disk_usage);
            serializer.Write(this.gpu_usage);
        }

        public override string ToString()
        {
            return "NUCStatisticsMsg: " +
            "\ntimestamp: " + timestamp.ToString() +
            "\ncpu_percentage: " + cpu_percentage.ToString() +
            "\nram_usage: " + ram_usage.ToString() +
            "\ndisk_usage: " + disk_usage.ToString() +
            "\ngpu_usage: " + gpu_usage.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
