//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Autonav
{
    [Serializable]
    public class PerformanceMsg : Message
    {
        public const string k_RosMessageName = "autonav_msgs/Performance";
        public override string RosMessageName => k_RosMessageName;

        public string name;
        public ushort elapsed;

        public PerformanceMsg()
        {
            this.name = "";
            this.elapsed = 0;
        }

        public PerformanceMsg(string name, ushort elapsed)
        {
            this.name = name;
            this.elapsed = elapsed;
        }

        public static PerformanceMsg Deserialize(MessageDeserializer deserializer) => new PerformanceMsg(deserializer);

        private PerformanceMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.name);
            deserializer.Read(out this.elapsed);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.name);
            serializer.Write(this.elapsed);
        }

        public override string ToString()
        {
            return "PerformanceMsg: " +
            "\nname: " + name.ToString() +
            "\nelapsed: " + elapsed.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
