//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Autonav
{
    [Serializable]
    public class SystemStateMsg : Message
    {
        public const string k_RosMessageName = "autonav_msgs/SystemState";
        public override string RosMessageName => k_RosMessageName;

        public byte state;
        public bool mobility;

        public SystemStateMsg()
        {
            this.state = 0;
            this.mobility = false;
        }

        public SystemStateMsg(byte state, bool mobility)
        {
            this.state = state;
            this.mobility = mobility;
        }

        public static SystemStateMsg Deserialize(MessageDeserializer deserializer) => new SystemStateMsg(deserializer);

        private SystemStateMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.state);
            deserializer.Read(out this.mobility);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.state);
            serializer.Write(this.mobility);
        }

        public override string ToString()
        {
            return "SystemStateMsg: " +
            "\nstate: " + state.ToString() +
            "\nmobility: " + mobility.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
