//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Autonav
{
    [Serializable]
    public class UltrasonicMsg : Message
    {
        public const string k_RosMessageName = "autonav_msgs/Ultrasonic";
        public override string RosMessageName => k_RosMessageName;

        public byte id;
        public ushort distance;

        public UltrasonicMsg()
        {
            this.id = 0;
            this.distance = 0;
        }

        public UltrasonicMsg(byte id, ushort distance)
        {
            this.id = id;
            this.distance = distance;
        }

        public static UltrasonicMsg Deserialize(MessageDeserializer deserializer) => new UltrasonicMsg(deserializer);

        private UltrasonicMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.id);
            deserializer.Read(out this.distance);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.id);
            serializer.Write(this.distance);
        }

        public override string ToString()
        {
            return "UltrasonicMsg: " +
            "\nid: " + id.ToString() +
            "\ndistance: " + distance.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
