//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Autonav
{
    [Serializable]
    public class AngularPIDStatisticsMsg : Message
    {
        public const string k_RosMessageName = "autonav_msgs/AngularPIDStatistics";
        public override string RosMessageName => k_RosMessageName;

        public short angular_velocity;
        public short angular_velocity_setpoint;

        public AngularPIDStatisticsMsg()
        {
            this.angular_velocity = 0;
            this.angular_velocity_setpoint = 0;
        }

        public AngularPIDStatisticsMsg(short angular_velocity, short angular_velocity_setpoint)
        {
            this.angular_velocity = angular_velocity;
            this.angular_velocity_setpoint = angular_velocity_setpoint;
        }

        public static AngularPIDStatisticsMsg Deserialize(MessageDeserializer deserializer) => new AngularPIDStatisticsMsg(deserializer);

        private AngularPIDStatisticsMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.angular_velocity);
            deserializer.Read(out this.angular_velocity_setpoint);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.angular_velocity);
            serializer.Write(this.angular_velocity_setpoint);
        }

        public override string ToString()
        {
            return "AngularPIDStatisticsMsg: " +
            "\nangular_velocity: " + angular_velocity.ToString() +
            "\nangular_velocity_setpoint: " + angular_velocity_setpoint.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
