//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Autonav
{
    [Serializable]
    public class CanStatsMsg : Message
    {
        public const string k_RosMessageName = "autonav_msgs/CanStats";
        public override string RosMessageName => k_RosMessageName;

        public ushort tx;
        public ushort rx;

        public CanStatsMsg()
        {
            this.tx = 0;
            this.rx = 0;
        }

        public CanStatsMsg(ushort tx, ushort rx)
        {
            this.tx = tx;
            this.rx = rx;
        }

        public static CanStatsMsg Deserialize(MessageDeserializer deserializer) => new CanStatsMsg(deserializer);

        private CanStatsMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.tx);
            deserializer.Read(out this.rx);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.tx);
            serializer.Write(this.rx);
        }

        public override string ToString()
        {
            return "CanStatsMsg: " +
            "\ntx: " + tx.ToString() +
            "\nrx: " + rx.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
