//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Autonav
{
    [Serializable]
    public class CommandMsg : Message
    {
        public const string k_RosMessageName = "autonav_msgs/Command";
        public override string RosMessageName => k_RosMessageName;

        public string method;
        public string @params;

        public CommandMsg()
        {
            this.method = "";
            this.@params = "";
        }

        public CommandMsg(string method, string @params)
        {
            this.method = method;
            this.@params = @params;
        }

        public static CommandMsg Deserialize(MessageDeserializer deserializer) => new CommandMsg(deserializer);

        private CommandMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.method);
            deserializer.Read(out this.@params);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.method);
            serializer.Write(this.@params);
        }

        public override string ToString()
        {
            return "CommandMsg: " +
            "\nmethod: " + method.ToString() +
            "\n@params: " + @params.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
