//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Autonav
{
    [Serializable]
    public class ConbusMsg : Message
    {
        public const string k_RosMessageName = "autonav_msgs/Conbus";
        public override string RosMessageName => k_RosMessageName;

        public uint id;
        public byte[] data;
        public long iterator = -1;

        public ConbusMsg()
        {
            this.id = 0;
            this.data = new byte[0];
        }

        public ConbusMsg(uint id, byte[] data, long iterator)
        {
            this.id = id;
            this.data = data;
            this.iterator = iterator;
        }

        public static ConbusMsg Deserialize(MessageDeserializer deserializer) => new ConbusMsg(deserializer);

        private ConbusMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.id);
            deserializer.Read(out this.data, sizeof(byte), deserializer.ReadLength());
            deserializer.Read(out this.iterator);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.id);
            serializer.WriteLength(this.data);
            serializer.Write(this.data);
            serializer.Write(this.iterator);
        }

        public override string ToString()
        {
            return "ConbusMsg: " +
            "\nid: " + id.ToString() +
            "\ndata: " + System.String.Join(", ", data.ToList()) +
            "\niterator: " + iterator.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
