//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Autonav
{
    [Serializable]
    public class ConfigurationBroadcastMsg : Message
    {
        public const string k_RosMessageName = "autonav_msgs/ConfigurationBroadcast";
        public override string RosMessageName => k_RosMessageName;

        public string[] target_nodes;

        public ConfigurationBroadcastMsg()
        {
            this.target_nodes = new string[0];
        }

        public ConfigurationBroadcastMsg(string[] target_nodes)
        {
            this.target_nodes = target_nodes;
        }

        public static ConfigurationBroadcastMsg Deserialize(MessageDeserializer deserializer) => new ConfigurationBroadcastMsg(deserializer);

        private ConfigurationBroadcastMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.target_nodes, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.target_nodes);
            serializer.Write(this.target_nodes);
        }

        public override string ToString()
        {
            return "ConfigurationBroadcastMsg: " +
            "\ntarget_nodes: " + System.String.Join(", ", target_nodes.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
