//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Autonav
{
    [Serializable]
    public class GPSFeedbackMsg : Message
    {
        public const string k_RosMessageName = "autonav_msgs/GPSFeedback";
        public override string RosMessageName => k_RosMessageName;

        public double latitude;
        public double longitude;
        public double altitude;
        public sbyte num_satellites;
        public sbyte gps_fix;
        //  0-8, where 0 is not tracking and 8 is 3D fix with RTK solution

        public GPSFeedbackMsg()
        {
            this.latitude = 0.0;
            this.longitude = 0.0;
            this.altitude = 0.0;
            this.num_satellites = 0;
            this.gps_fix = 0;
        }

        public GPSFeedbackMsg(double latitude, double longitude, double altitude, sbyte num_satellites, sbyte gps_fix)
        {
            this.latitude = latitude;
            this.longitude = longitude;
            this.altitude = altitude;
            this.num_satellites = num_satellites;
            this.gps_fix = gps_fix;
        }

        public static GPSFeedbackMsg Deserialize(MessageDeserializer deserializer) => new GPSFeedbackMsg(deserializer);

        private GPSFeedbackMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.latitude);
            deserializer.Read(out this.longitude);
            deserializer.Read(out this.altitude);
            deserializer.Read(out this.num_satellites);
            deserializer.Read(out this.gps_fix);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.latitude);
            serializer.Write(this.longitude);
            serializer.Write(this.altitude);
            serializer.Write(this.num_satellites);
            serializer.Write(this.gps_fix);
        }

        public override string ToString()
        {
            return "GPSFeedbackMsg: " +
            "\nlatitude: " + latitude.ToString() +
            "\nlongitude: " + longitude.ToString() +
            "\naltitude: " + altitude.ToString() +
            "\nnum_satellites: " + num_satellites.ToString() +
            "\ngps_fix: " + gps_fix.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
