//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Autonav
{
    [Serializable]
    public class HardwarePerformanceMsg : Message
    {
        public const string k_RosMessageName = "autonav_msgs/HardwarePerformance";
        public override string RosMessageName => k_RosMessageName;

        public double cpu;
        public double memory;
        public string temp;

        public HardwarePerformanceMsg()
        {
            this.cpu = 0.0;
            this.memory = 0.0;
            this.temp = "";
        }

        public HardwarePerformanceMsg(double cpu, double memory, string temp)
        {
            this.cpu = cpu;
            this.memory = memory;
            this.temp = temp;
        }

        public static HardwarePerformanceMsg Deserialize(MessageDeserializer deserializer) => new HardwarePerformanceMsg(deserializer);

        private HardwarePerformanceMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.cpu);
            deserializer.Read(out this.memory);
            deserializer.Read(out this.temp);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.cpu);
            serializer.Write(this.memory);
            serializer.Write(this.temp);
        }

        public override string ToString()
        {
            return "HardwarePerformanceMsg: " +
            "\ncpu: " + cpu.ToString() +
            "\nmemory: " + memory.ToString() +
            "\ntemp: " + temp.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
