//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Autonav
{
    [Serializable]
    public class IMUDataMsg : Message
    {
        public const string k_RosMessageName = "autonav_msgs/IMUData";
        public override string RosMessageName => k_RosMessageName;

        public double yaw;
        public double pitch;
        public double roll;
        public double accel_x;
        public double accel_y;
        public double accel_z;
        public double angular_x;
        public double angular_y;
        public double angular_z;
        public sbyte status;

        public IMUDataMsg()
        {
            this.yaw = 0.0;
            this.pitch = 0.0;
            this.roll = 0.0;
            this.accel_x = 0.0;
            this.accel_y = 0.0;
            this.accel_z = 0.0;
            this.angular_x = 0.0;
            this.angular_y = 0.0;
            this.angular_z = 0.0;
            this.status = 0;
        }

        public IMUDataMsg(double yaw, double pitch, double roll, double accel_x, double accel_y, double accel_z, double angular_x, double angular_y, double angular_z, sbyte status)
        {
            this.yaw = yaw;
            this.pitch = pitch;
            this.roll = roll;
            this.accel_x = accel_x;
            this.accel_y = accel_y;
            this.accel_z = accel_z;
            this.angular_x = angular_x;
            this.angular_y = angular_y;
            this.angular_z = angular_z;
            this.status = status;
        }

        public static IMUDataMsg Deserialize(MessageDeserializer deserializer) => new IMUDataMsg(deserializer);

        private IMUDataMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.yaw);
            deserializer.Read(out this.pitch);
            deserializer.Read(out this.roll);
            deserializer.Read(out this.accel_x);
            deserializer.Read(out this.accel_y);
            deserializer.Read(out this.accel_z);
            deserializer.Read(out this.angular_x);
            deserializer.Read(out this.angular_y);
            deserializer.Read(out this.angular_z);
            deserializer.Read(out this.status);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.yaw);
            serializer.Write(this.pitch);
            serializer.Write(this.roll);
            serializer.Write(this.accel_x);
            serializer.Write(this.accel_y);
            serializer.Write(this.accel_z);
            serializer.Write(this.angular_x);
            serializer.Write(this.angular_y);
            serializer.Write(this.angular_z);
            serializer.Write(this.status);
        }

        public override string ToString()
        {
            return "IMUDataMsg: " +
            "\nyaw: " + yaw.ToString() +
            "\npitch: " + pitch.ToString() +
            "\nroll: " + roll.ToString() +
            "\naccel_x: " + accel_x.ToString() +
            "\naccel_y: " + accel_y.ToString() +
            "\naccel_z: " + accel_z.ToString() +
            "\nangular_x: " + angular_x.ToString() +
            "\nangular_y: " + angular_y.ToString() +
            "\nangular_z: " + angular_z.ToString() +
            "\nstatus: " + status.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
