//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Autonav
{
    [Serializable]
    public class LinearPIDStatisticsMsg : Message
    {
        public const string k_RosMessageName = "autonav_msgs/LinearPIDStatistics";
        public override string RosMessageName => k_RosMessageName;

        public short forward_velocity;
        public short forward_velocity_setpoint;
        public short sideways_velocity;
        public short sideways_velocity_setpoint;

        public LinearPIDStatisticsMsg()
        {
            this.forward_velocity = 0;
            this.forward_velocity_setpoint = 0;
            this.sideways_velocity = 0;
            this.sideways_velocity_setpoint = 0;
        }

        public LinearPIDStatisticsMsg(short forward_velocity, short forward_velocity_setpoint, short sideways_velocity, short sideways_velocity_setpoint)
        {
            this.forward_velocity = forward_velocity;
            this.forward_velocity_setpoint = forward_velocity_setpoint;
            this.sideways_velocity = sideways_velocity;
            this.sideways_velocity_setpoint = sideways_velocity_setpoint;
        }

        public static LinearPIDStatisticsMsg Deserialize(MessageDeserializer deserializer) => new LinearPIDStatisticsMsg(deserializer);

        private LinearPIDStatisticsMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.forward_velocity);
            deserializer.Read(out this.forward_velocity_setpoint);
            deserializer.Read(out this.sideways_velocity);
            deserializer.Read(out this.sideways_velocity_setpoint);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.forward_velocity);
            serializer.Write(this.forward_velocity_setpoint);
            serializer.Write(this.sideways_velocity);
            serializer.Write(this.sideways_velocity_setpoint);
        }

        public override string ToString()
        {
            return "LinearPIDStatisticsMsg: " +
            "\nforward_velocity: " + forward_velocity.ToString() +
            "\nforward_velocity_setpoint: " + forward_velocity_setpoint.ToString() +
            "\nsideways_velocity: " + sideways_velocity.ToString() +
            "\nsideways_velocity_setpoint: " + sideways_velocity_setpoint.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
