//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Autonav
{
    [Serializable]
    public class MotorStatisticsMsg : Message
    {
        public const string k_RosMessageName = "autonav_msgs/MotorStatistics";
        public override string RosMessageName => k_RosMessageName;

        public short left_drive_motor_output;
        public short left_steer_motor_output;
        public short right_drive_motor_output;
        public short right_steer_motor_output;

        public MotorStatisticsMsg()
        {
            this.left_drive_motor_output = 0;
            this.left_steer_motor_output = 0;
            this.right_drive_motor_output = 0;
            this.right_steer_motor_output = 0;
        }

        public MotorStatisticsMsg(short left_drive_motor_output, short left_steer_motor_output, short right_drive_motor_output, short right_steer_motor_output)
        {
            this.left_drive_motor_output = left_drive_motor_output;
            this.left_steer_motor_output = left_steer_motor_output;
            this.right_drive_motor_output = right_drive_motor_output;
            this.right_steer_motor_output = right_steer_motor_output;
        }

        public static MotorStatisticsMsg Deserialize(MessageDeserializer deserializer) => new MotorStatisticsMsg(deserializer);

        private MotorStatisticsMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.left_drive_motor_output);
            deserializer.Read(out this.left_steer_motor_output);
            deserializer.Read(out this.right_drive_motor_output);
            deserializer.Read(out this.right_steer_motor_output);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.left_drive_motor_output);
            serializer.Write(this.left_steer_motor_output);
            serializer.Write(this.right_drive_motor_output);
            serializer.Write(this.right_steer_motor_output);
        }

        public override string ToString()
        {
            return "MotorStatisticsMsg: " +
            "\nleft_drive_motor_output: " + left_drive_motor_output.ToString() +
            "\nleft_steer_motor_output: " + left_steer_motor_output.ToString() +
            "\nright_drive_motor_output: " + right_drive_motor_output.ToString() +
            "\nright_steer_motor_output: " + right_steer_motor_output.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
