//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Autonav
{
    [Serializable]
    public class MotorInputMsg : Message
    {
        public const string k_RosMessageName = "autonav_msgs/MotorInput";
        public override string RosMessageName => k_RosMessageName;

        public float forward_velocity = 0f;
        public float sideways_velocity = 0f;
        public float angular_velocity = 0f;

        public MotorInputMsg()
        {
        }

        public MotorInputMsg(float forward_velocity, float sideways_velocity, float angular_velocity)
        {
            this.forward_velocity = forward_velocity;
            this.sideways_velocity = sideways_velocity;
            this.angular_velocity = angular_velocity;
        }

        public static MotorInputMsg Deserialize(MessageDeserializer deserializer) => new MotorInputMsg(deserializer);

        private MotorInputMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.forward_velocity);
            deserializer.Read(out this.sideways_velocity);
            deserializer.Read(out this.angular_velocity);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.forward_velocity);
            serializer.Write(this.sideways_velocity);
            serializer.Write(this.angular_velocity);
        }

        public override string ToString()
        {
            return "MotorInputMsg: " +
            "\nforward_velocity: " + forward_velocity.ToString() +
            "\nsideways_velocity: " + sideways_velocity.ToString() +
            "\nangular_velocity: " + angular_velocity.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
