//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Autonav
{
    [Serializable]
    public class SafetyLightsMsg : Message
    {
        public const string k_RosMessageName = "autonav_msgs/SafetyLights";
        public override string RosMessageName => k_RosMessageName;

        public bool autonomous;
        public byte red;
        public byte green;
        public byte blue;

        public SafetyLightsMsg()
        {
            this.autonomous = false;
            this.red = 0;
            this.green = 0;
            this.blue = 0;
        }

        public SafetyLightsMsg(bool autonomous, byte red, byte green, byte blue)
        {
            this.autonomous = autonomous;
            this.red = red;
            this.green = green;
            this.blue = blue;
        }

        public static SafetyLightsMsg Deserialize(MessageDeserializer deserializer) => new SafetyLightsMsg(deserializer);

        private SafetyLightsMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.autonomous);
            deserializer.Read(out this.red);
            deserializer.Read(out this.green);
            deserializer.Read(out this.blue);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.autonomous);
            serializer.Write(this.red);
            serializer.Write(this.green);
            serializer.Write(this.blue);
        }

        public override string ToString()
        {
            return "SafetyLightsMsg: " +
            "\nautonomous: " + autonomous.ToString() +
            "\nred: " + red.ToString() +
            "\ngreen: " + green.ToString() +
            "\nblue: " + blue.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
