//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Autonav
{
    [Serializable]
    public class SafetyLightsMsg : Message
    {
        public const string k_RosMessageName = "autonav_msgs/SafetyLights";
        public override string RosMessageName => k_RosMessageName;

        public byte mode;
        public byte brightness;
        public byte red;
        public byte green;
        public byte blue;
        public byte blink_period;

        public SafetyLightsMsg()
        {
            this.mode = 0;
            this.brightness = 0;
            this.red = 0;
            this.green = 0;
            this.blue = 0;
            this.blink_period = 0;
        }

        public SafetyLightsMsg(byte mode, byte brightness, byte red, byte green, byte blue, byte blink_period)
        {
            this.mode = mode;
            this.brightness = brightness;
            this.red = red;
            this.green = green;
            this.blue = blue;
            this.blink_period = blink_period;
        }

        public static SafetyLightsMsg Deserialize(MessageDeserializer deserializer) => new SafetyLightsMsg(deserializer);

        private SafetyLightsMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.mode);
            deserializer.Read(out this.brightness);
            deserializer.Read(out this.red);
            deserializer.Read(out this.green);
            deserializer.Read(out this.blue);
            deserializer.Read(out this.blink_period);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.mode);
            serializer.Write(this.brightness);
            serializer.Write(this.red);
            serializer.Write(this.green);
            serializer.Write(this.blue);
            serializer.Write(this.blink_period);
        }

        public override string ToString()
        {
            return "SafetyLightsMsg: " +
            "\nmode: " + mode.ToString() +
            "\nbrightness: " + brightness.ToString() +
            "\nred: " + red.ToString() +
            "\ngreen: " + green.ToString() +
            "\nblue: " + blue.ToString() +
            "\nblink_period: " + blink_period.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
