//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Autonav
{
    [Serializable]
    public class SwerveAbsoluteFeedbackMsg : Message
    {
        public const string k_RosMessageName = "autonav_msgs/SwerveAbsoluteFeedback";
        public override string RosMessageName => k_RosMessageName;

        public double position_fl;
        public double position_fr;
        public double position_bl;
        public double position_br;

        public SwerveAbsoluteFeedbackMsg()
        {
            this.position_fl = 0.0;
            this.position_fr = 0.0;
            this.position_bl = 0.0;
            this.position_br = 0.0;
        }

        public SwerveAbsoluteFeedbackMsg(double position_fl, double position_fr, double position_bl, double position_br)
        {
            this.position_fl = position_fl;
            this.position_fr = position_fr;
            this.position_bl = position_bl;
            this.position_br = position_br;
        }

        public static SwerveAbsoluteFeedbackMsg Deserialize(MessageDeserializer deserializer) => new SwerveAbsoluteFeedbackMsg(deserializer);

        private SwerveAbsoluteFeedbackMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.position_fl);
            deserializer.Read(out this.position_fr);
            deserializer.Read(out this.position_bl);
            deserializer.Read(out this.position_br);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.position_fl);
            serializer.Write(this.position_fr);
            serializer.Write(this.position_bl);
            serializer.Write(this.position_br);
        }

        public override string ToString()
        {
            return "SwerveAbsoluteFeedbackMsg: " +
            "\nposition_fl: " + position_fl.ToString() +
            "\nposition_fr: " + position_fr.ToString() +
            "\nposition_bl: " + position_bl.ToString() +
            "\nposition_br: " + position_br.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
