//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Autonav
{
    [Serializable]
    public class SwerveFeedbackMsg : Message
    {
        public const string k_RosMessageName = "autonav_msgs/SwerveFeedback";
        public override string RosMessageName => k_RosMessageName;

        public int module;
        public double desired_x_vel;
        public double desired_y_vel;
        public double desired_angular_vel;
        public double measured_x_vel;
        public double measured_y_vel;
        public double measured_angular_vel;

        public SwerveFeedbackMsg()
        {
            this.module = 0;
            this.desired_x_vel = 0.0;
            this.desired_y_vel = 0.0;
            this.desired_angular_vel = 0.0;
            this.measured_x_vel = 0.0;
            this.measured_y_vel = 0.0;
            this.measured_angular_vel = 0.0;
        }

        public SwerveFeedbackMsg(int module, double desired_x_vel, double desired_y_vel, double desired_angular_vel, double measured_x_vel, double measured_y_vel, double measured_angular_vel)
        {
            this.module = module;
            this.desired_x_vel = desired_x_vel;
            this.desired_y_vel = desired_y_vel;
            this.desired_angular_vel = desired_angular_vel;
            this.measured_x_vel = measured_x_vel;
            this.measured_y_vel = measured_y_vel;
            this.measured_angular_vel = measured_angular_vel;
        }

        public static SwerveFeedbackMsg Deserialize(MessageDeserializer deserializer) => new SwerveFeedbackMsg(deserializer);

        private SwerveFeedbackMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.module);
            deserializer.Read(out this.desired_x_vel);
            deserializer.Read(out this.desired_y_vel);
            deserializer.Read(out this.desired_angular_vel);
            deserializer.Read(out this.measured_x_vel);
            deserializer.Read(out this.measured_y_vel);
            deserializer.Read(out this.measured_angular_vel);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.module);
            serializer.Write(this.desired_x_vel);
            serializer.Write(this.desired_y_vel);
            serializer.Write(this.desired_angular_vel);
            serializer.Write(this.measured_x_vel);
            serializer.Write(this.measured_y_vel);
            serializer.Write(this.measured_angular_vel);
        }

        public override string ToString()
        {
            return "SwerveFeedbackMsg: " +
            "\nmodule: " + module.ToString() +
            "\ndesired_x_vel: " + desired_x_vel.ToString() +
            "\ndesired_y_vel: " + desired_y_vel.ToString() +
            "\ndesired_angular_vel: " + desired_angular_vel.ToString() +
            "\nmeasured_x_vel: " + measured_x_vel.ToString() +
            "\nmeasured_y_vel: " + measured_y_vel.ToString() +
            "\nmeasured_angular_vel: " + measured_angular_vel.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
