//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Autonav
{
    [Serializable]
    public class ZeroEncodersMsg : Message
    {
        public const string k_RosMessageName = "autonav_msgs/ZeroEncoders";
        public override string RosMessageName => k_RosMessageName;

        public uint id;
        public byte which_encoder;

        public ZeroEncodersMsg()
        {
            this.id = 0;
            this.which_encoder = 0;
        }

        public ZeroEncodersMsg(uint id, byte which_encoder)
        {
            this.id = id;
            this.which_encoder = which_encoder;
        }

        public static ZeroEncodersMsg Deserialize(MessageDeserializer deserializer) => new ZeroEncodersMsg(deserializer);

        private ZeroEncodersMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.id);
            deserializer.Read(out this.which_encoder);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.id);
            serializer.Write(this.which_encoder);
        }

        public override string ToString()
        {
            return "ZeroEncodersMsg: " +
            "\nid: " + id.ToString() +
            "\nwhich_encoder: " + which_encoder.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
