//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Autonav
{
    [Serializable]
    public class SetDeviceStateRequest : Message
    {
        public const string k_RosMessageName = "autonav_msgs/SetDeviceState";
        public override string RosMessageName => k_RosMessageName;

        public string device;
        public byte state;

        public SetDeviceStateRequest()
        {
            this.device = "";
            this.state = 0;
        }

        public SetDeviceStateRequest(string device, byte state)
        {
            this.device = device;
            this.state = state;
        }

        public static SetDeviceStateRequest Deserialize(MessageDeserializer deserializer) => new SetDeviceStateRequest(deserializer);

        private SetDeviceStateRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.device);
            deserializer.Read(out this.state);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.device);
            serializer.Write(this.state);
        }

        public override string ToString()
        {
            return "SetDeviceStateRequest: " +
            "\ndevice: " + device.ToString() +
            "\nstate: " + state.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
