//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Autonav
{
    [Serializable]
    public class SetSystemStateResponse : Message
    {
        public const string k_RosMessageName = "autonav_msgs/SetSystemState";
        public override string RosMessageName => k_RosMessageName;

        public bool ok;

        public SetSystemStateResponse()
        {
            this.ok = false;
        }

        public SetSystemStateResponse(bool ok)
        {
            this.ok = ok;
        }

        public static SetSystemStateResponse Deserialize(MessageDeserializer deserializer) => new SetSystemStateResponse(deserializer);

        private SetSystemStateResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.ok);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.ok);
        }

        public override string ToString()
        {
            return "SetSystemStateResponse: " +
            "\nok: " + ok.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
